version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    entrypoint: /entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=instagram.settings.local
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./instagram/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres-data:

